name: Build on Everything

on:
  workflow_dispatch:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened ]

jobs:
  ubuntu:
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: ubuntu-latest
    secrets: inherit
  
  windows:
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: windows-latest
    secrets: inherit
  
  macOS:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: macOS-latest
    secrets: inherit