name: Build on Everything

on:
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release # Release, Debug, RelWithDebInfo, MinSizeRel
  CMAKE_BUILD_PARALLEL_LEVEL: "" # Enable build parallelism

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get lastest CMake
      uses: lukka/get-cmake@latest

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgJsonGlob: vcpkg.json

    - name: Prepare for build (All)
      run: python -m pip install jinja2

    - name: run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: default
        buildPreset: default