name: Build on Everything

on:
  workflow_dispatch:
  release:
  push: 
  pull_request:

jobs:
  ubuntu:
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: ubuntu-latest
      saveArtifact: true
      ArtifactName: build-linux
    secrets: inherit
  
  windows:
    if: github.event_name == 'release' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: windows-latest
      saveArtifact: true
      ArtifactName: build-windows
    secrets: inherit
  
  macOS:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/SetupAndBuild.yml
    with:
      system: macOS-latest
      saveArtifact: true
      ArtifactName: build-macOS
    secrets: inherit