name: Setup and build

on:
  workflow_call:
    inputs:
      system:
        required: true
        type: string
      buildType:
        required: false
        default: Relase
        type: string
      saveArtifact:
        required: false
        default: false
        type: boolean
      ArtifactName:
        required: false
        default: build-artifact
        type: string
    
env:
  CMAKE_BUILD_TYPE: ${{ inputs.buildType }} # Release, Debug, RelWithDebInfo, MinSizeRel
  CMAKE_BUILD_PARALLEL_LEVEL: "" # Enable build parallelism

jobs:
  build:
    name: build
    runs-on: ${{ inputs.system }}
       
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get lastest CMake
      uses: lukka/get-cmake@latest

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-use-cache: true
        
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgJsonGlob: vcpkg.json

    - name: Prepare for build (Ubuntu)
      if: contains( inputs.system, 'ubuntu' )
      run: sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libpthread-stubs0-dev

    - name: run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: default
        buildPreset: default

    - name: Archive production artifacts
      if: inputs.saveArtifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.ArtifactName }}
        path: out/install/*.app